spring.application.name=subscription-intelligence-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/subscription_intelligence}
spring.datasource.username=${DB_USERNAME:athiselvam}
spring.datasource.password=${DB_PASSWORD:selvam2024}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

app.cache.warming.cron=${CACHE_WARMING_CRON:0 0 2 * * SUN}

app.notification.renewal.cron=${NOTIFICATION_RENEWAL_CRON:0 0 8 * * *}
app.notification.renewal-window-days=${NOTIFICATION_RENEWAL_WINDOW_DAYS:7}